$(document).ready(function() {
	
	var book = {
		chris: '<p>Chris Johnson is a sophomore at the University of Nebraska-Lincoln\'s Jeffrey S Raikes School for Computer Science and Management. He is currently double majoring in computer science and economics, and has a strong passion in regional economic development and energy. He was born in Parkville, Missouri, a small suburb of Kansas City. He enjoys watching movies, reading books, keeping up with global politics, and playing loud rock songs on his Alvarez guitar.</p><p>Chris maintains the website for the World Energy Project. He helps with presentation, publicity, fundraising, and general team cheerleading. His interest in developmental economics began in high school, and after being inspired by several stories of entrepreneurial philanthropy in Africa during college was asked by Ashley to be a part of the World Energy Project team.  He\'s very excited to be working on this project and looks forward to future philanthropic efforts.</p>',
		emily: '<p>Emily Olig is a freshman at the University of Nebraska - Lincoln studying Biological Systems Engineering with a minor in Dance. Upon graduation, she hopes to research and implement renewable energy systems both in developed and developing countries. She believes the World Energy Project is exactly what she is meant to be doing to supplement her studies and personal growth, and she is very excited to be a part of such a great organization.</p><p>Emily is a native of Fargo, North Dakota, but loves attending school in Nebraska. She enjoys taking time off from her busy schedule to take dance classes through UNL\'s dance program and spend time with friends and sorority sisters.</p>',
		obama: '<p>Barack Hussein Obama II is the 44th and current President of the United States. He is the first African American to hold the office. Obama previously served as a United States Senator from Illinois, from January 2005 until he resigned after his election to the presidency in November 2008.</p><p>A native of Honolulu, Hawaii, Obama is a graduate of Columbia University and Harvard Law School, where he was the president of the Harvard Law Review. He was a community organizer in Chicago before earning his law degree. He worked as a civil rights attorney in Chicago and taught constitutional law at the University of Chicago Law School from 1992 to 2004.</p>',
		kyle: '<p>Kyle Curry is a Junior at the University of Nebraska-Lincoln\'s College of Business Administration. He is studying Finance and working on a minor in Energy Science-Economics. He is from Columbus Nebraska, home of Nebraska Public Power District\'s headquarters where both of his parents have worked since he can remember. Some hobbies of his are discovering music, going to shows, watching movies, U.S. soccer, riding his bike, and just hanging out with his friends.</p><p>Kyle is in charge of the finances of The World Energy Project as well as helping other groups involved in The World Energy Project. He became interested in energy at an early age with both of his parents worked in the energy field. His interests in the energy field expanded late in high school and early in college with the realization that human induced Climate Change is something we can no longer ignore. He feels that there must be energy reform in our country and around the world to help grow economies and create better lives for all people.</p>',
		chrisl: '<p>Chris Lander is a third year student in the College of Architecture at the University of Nebraska-Lincoln. He grew up in Omaha, Nebraska before moving to Lincoln to attend college. During the school year, Chris maintains a rigorous schedule, balancing classes, architecture studio projects, faculty-sponsored undergraduate research, and of course, The World Energy Project.</p><p>Outside of schoolwork, Chris enjoys playing soccer, exploring Lincoln on his bicycle, watching movies with friends, and following current events. He is very interested in sustainable design and emerging developments regarding world-wide energy consumption. Chris sees The World Energy Project as an excellent opportunity to help the world make a transition toward a sustainable future, and he is very excited to work alongside talented students and faculty from other fields.</p>',
		michael: '<p>Michael Trogdon is an Omaha, NE native and is currently a junior at the University of Nebraska-Lincoln. He is pursuing a double major in Mathematics and Mechanical Engineering. Michael\'s research interests include the study of numerical approximations to null controllability of systems of equations that are physically relevant, including the wave equation among others.</p><p>Outside of school and work Michael enjoys watching/collecting movies, snowboarding, travelling, reading, and playing basketball. He is also very interested in the future of renewable energy around the world and is excited about the challenges facing the engineering community in the years to come. The World Energy Project for him is the perfect opportunity to actually make a difference and help an amazing team reach their goals in any way he can.</p>',
		casey: '<p>Casey Heier is a junior at the University of Nebraska-Lincoln majoring in Biological Systems Engineering with minors in Energy Sciences and Chemistry. He thoroughly enjoys working on his research projects involving sustainable energy systems, climate change issues, and energy policy. Casey was born in Columbus, Nebraska and loves returning home and spending time outdoors.</p><p>In his free time, he also plays the piano, hangs out with his fraternity brothers, helps the homeless in Lincoln, and rides his bike everywhere and anywhere. Casey sees The World Energy Project as the perfect opportunity to use his talents and interests to make a positive impact in the lives of people around the world.</p>',
		ashley: '<p>Ashley Schmidt is a junior biological systems engineering major with a minor in Energy Sciences and is CEO of The World Energy Project. She became interested in energy engineering when she lived in Mali, West Africa in 2008, where she worked at the Koutiala Hospital for Women and Children. Ashley is passionate about using her engineering skills to develop opportunities for those in underdeveloped countries, and to engage her peers in similar humanitarian ventures.</p><p>Ashley was inspired to found The World Energy Project after learning about the solar panel installation project at the hospital and talking to Grant Stanley about the possibility of taking a team of UNL students to help with the project. She spoke with Global Partners in Hope about the possibility of partnering with them for the Koutiala project and was excited when GPiH suggested that The World Energy Project become a joint-venture with them. Ashley enjoys being outdoors in her free time, mountain biking, skateboarding and playing ultimate frisbee and soccer. Ashley is excited about working with the team on the Koutiala project and about developing future opportunities for WEP.</p>',
		eric: '<p>Eric Svingen is an Omaha native and senior physics major at Creighton University. He works part-time in the Condensed Matter Research Group, where he investigates the liquid-glass transition with photon correlation spectroscopy techniques. In 2010, Eric worked on the Omaha Renewable Energy Project, which deployed 120 kW of solar capacity on the Creighton campus. This system is now the largest producer of solar power in Nebraska.</p><p>Eric is passionate about engineering for social justice and sustainable community development. He intends to earn a graduate degree in environmental engineering, and then work on water treatment projects in the developing world. He is a project leader for the World Energy Project, leading an upcoming initiative in Kenya. He believes WEP is an excellent organization, and is thrilled to be working with so many smart and entrepreneurial team members.</p>',
		grant: '<p>Grant Stanley is an entrepreneur at heart. His day job is building Contemporary Analysis a company that develops mathematical systems to solve everyday business ideas such as building strategic forecasts, lead generation systems and improving employee/management communication. His goal with Contemporary Analysis is to change the way businesses think about systems.</p><p>He is committed to donating his time and entrepreneurial abilities helping people make their dreams come true. He decided to become involved with the World Energy Project as the Chairman of the Board, after talking with Ashley Schmidt about her passion for Africa and localized renewable energy and combining both to help improve peoples lives. He is excited to be involved and is confident that the World Energy Project will be able to succeed.</p>',
		sara: '<p>Sara Leimbach is an interactive enthusiast and creative junkie currently majoring in Advertising with an emphasis in Interactive Strategy and Design at UNL.</p><p>Sara leads the marketing efforts of the World Energy Project, including the creation and implementation of WEP\'s new website and re-branding. She also assists with strategy, publicity, fundraising, and the formation of presentations. Most importantly, Sara is looking forward to helping the World Energy Project not only reach, but surpass its goals.</p><p>When she isn\'t working on her laptop, Sara relaxes with yoga and hits up concerts at local venues. She aspires to form a World Energy Project sand volleyball team and create a stellar \'ACE\' cheer involving renewable energy references.</p>',
		chrish: '<p>Chris is a senior Biological Systems Engineering major from Omaha, Nebraska whose interests have ranged from music and entertainment to Biomedical Engineering and Renewable Energies.  He became passionate about the World Energy Project when he found their dreams align with his:  To maximize philanthropic good using positive, progressive technologies where they are needed most.  He believes in the success of the World Energy Project due to the amazing passion he found in his fellow members of the organization.  His plans after graduation are to use his enthusiasm for the project to get him situated in a lifestyle in Mali where he can directly give hands-on aid.</p>',
	};
	
	$('.member').hover(function() {
		var theInfo = getInfo(this.id);
		var theString = '<div class="extend">'+theInfo+'</div>';
		$(theString).appendTo(this);
	}, function() {
		$('.extend').remove();
	});
	

	function getInfo(id){
		return book[id];
	};
	
});

